# Generated by Django 2.2.3 on 2019-07-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='foto_barang')),
                ('harga', models.IntegerField(verbose_name='Rupiah')),
                ('link_detail', models.CharField(default='lihat detail', max_length=200)),
                ('deskripsi1', models.TextField(blank=True, verbose_name='deskripsi 1')),
                ('deskripsi2', models.TextField(blank=True, verbose_name='deskripsi 3')),
            ],
        ),
    ]
