# Generated by Django 2.2.3 on 2019-07-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko_online', '0002_remove_barang_deskripsi2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='deskripsi1',
            new_name='deskripsi',
        ),
    ]
