# Generated by Django 2.2.3 on 2019-07-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_online', '0003_auto_20190725_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='deskripsi',
            field=models.TextField(blank=True, verbose_name='deskripsi'),
        ),
    ]
